let m1 = new Map();
let o1 = {a: 'A'};
m1.set(o1, 'aA');
console.log(m1);
m1.set('b', 'B');
console.log(m1);
console.log(m1.get(o1));
let m2 = new Map([['b', 'B'], ['c', 'C']]);
console.log(m2);
console.log(m2.get('b'));
console.log(m2.size);
console.log(m2.set('d', 'D').set('g', 'G'));
console.log([...m2]);